name: DeployToGitHubPages
env:
  PUBLISH_DIR: './Chapter 12/Chapter_12_GitHubActions_Examples/bin/Release/net5.0/publish/wwwroot'

on:
  push:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest    
          
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Publish app
      run: dotnet publish -c Release './Chapter 12/Chapter_12_GitHubActions_Examples/Chapter12.csproj'  
    
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myWASM
        path: './Chapter 12/Chapter_12_GitHubActions_Examples/bin/Release/net5.0/publish/wwwroot'            

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    - name: clear
      continue-on-error: true
      run: |
          git config --global user.name "Jeff Chilberto"
          git config --global user.email "chilberto@yahoo.com"
          
          git rm -rf . 
          git commit --allow-empty -m "root commit" 
          git push origin gh-pages
              
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: myWASM
        
    - name: Commit changes
      run: | 
          git add .
          git commit -m "publishing WASM"         
          git push            
